[package]
name = "reach"
version.workspace = true
edition.workspace = true
description = "Core P2P chat and connections functionality for Rustalk"
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
keywords = ["p2p", "chat", "encryption", "networking", "rustalk"]
categories = ["network-programming", "cryptography"]

[lib]
name = "reach"
crate-type = ["rlib"]

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
aes-gcm = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
regex = "1.0"
