[package]
name = "reach"
version = "0.1.0"
edition = "2021"
description = "P2P networking and encryption library for Rustalk"
license = "MIT"
authors = ["Rustalk Team"]

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
aes-gcm = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
futures = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
dirs = { workspace = true }
