[package]
name = "rus"
version = "0.0.0"
edition = "2021"
description = "CLI wrapper for Rustalk P2P chat"
license = "MIT"
authors = ["Rustalk Team"]
repository = "https://github.com/muhammad-fiaz/Rustalk"
homepage = "https://github.com/muhammad-fiaz/Rustalk"
readme = "../../README.md"
keywords = ["cli", "p2p", "chat", "terminal", "rustalk"]

[[bin]]
name = "rus"
path = "src/main.rs"

[dependencies]
reach = { path = "../reach" }
rustalk = { path = "../../rustalk" }
# For publishing, use these instead:
# reach = "0.0.0"
# rustalk = "0.0.0"
tokio = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
